### ISSUE TITLE
Using Metagol with rules containing more than two arguments?

### ISSUE THREAD

**Issue by joshuacrotts** [metagol/metagol#23]
Since I couldn't find a location for Q&A, I figured I'd post an issue here...

What I'm trying to do is learn a rule with an arity of _four_, but Metagol can't seem to deduce a solution from it. I'm working on some research related to argument mining, and any time I try to learn a rule with arity > 2, it doesn't want to work, even if I put the predicates in a list. 

Example of what I'm doing:
```

bk(a).
bk(b).

:- Pos [
   arg(arg1, [bk(a), bk(b), conclusion(a, b)])
], learn(Pos, []).

```
The issue with the above code is that it never produces a solution (takes literal minutes...).

Example of what I _want_ to do:

```

bk(a).
bk(b).

:- Pos [
   arg(arg1, bk(a), bk(b), conclusion(a, b))
], learn(Pos, []).

```

Does this make sense?

Edit: clarity.
**Edit 2:** Apparently, if I take out the constant arg1, it does terminate, but it never finds a solution. Note that my KB has plenty of examples like this, but it can't seem to derive the rule. 

Also, the rule I would like to actually deduce is arg(arg1, bk(a), bk(b), conclusion(a, b)) :- bk(a), bk(b). or something to that effect.

**Comment by andrewcropper** [comment]
Metagol can learn programs with higher-arity predicates, but it is pretty useless at doing so.

You would need to provide hand-crafted _metarules_, such as:

> metarule([P,Q,R], [P,A,B,C,D], [[Q,A,B,C,D],[R,A,B]]).

which means:

P(A,B,C,D):- Q(A,B,C,D),R(A,B).

These metarules are [impossible to precompute](https://arxiv.org/pdf/1907.10952.pdf), which is why Metagol is pretty useless at such problems.

I suggest using a different ILP system.  

We are currently working on a far better system called [Popper](https://github.com/rolfmorel/popper). It can easily handle higher-arity relations, but it is still a major work-in-progress. 

Otherwise perhaps try [Aleph](https://www.cs.ox.ac.uk/activities/programinduction/Aleph/aleph_toc.html), which can also easily handle higher-arity relations.

**Comment by JoshuaCrotts** [comment]
Gotcha... I'll keep on the lookout for Popper, and try Aleph too. Thanks for the information!
